<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Yahyya\taskmanager\App\Models\User;

class LabelTest extends TestCase
{

    use RefreshDatabase;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_user_can_add_labels()
    {
        $this->assertTrue(true);
    }
}
